config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to:'cocktails#index'

  resources :cocktails, only: [:index, :show, :create, :new] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
   resources :reviews, only: [:destroy]
    resources :cocktails, only: [:destroy]

  resources :cocktails do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
validates :name, uniqueness: true, presence: true
has_many :doses, dependent: :destroy
has_many :ingredients, through: :doses
has_one_attached :photo
has_many :reviews, dependent: :destroy
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :title, presence: true
  validates :content, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
    redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
def new
  @cocktail = Cocktail.find(params[:cocktail_id])
  @review = Review.new
end

  def create
    @review = Review.new(review_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<img src="https://images.unsplash.com/photo-1507383832450-e75a770318ea?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" class="img-fluid" alt="Responsive image">
  <div class="carousel-caption">
    <div class="animated fadeInDown">
      <div class="container h-100">
        <div class="d-flex h-100 text-center align-items-center">
          <div class="w-100 text-white">
          <%= link_to "Add a new Cocktail", new_cocktail_path , :class => "btn-cocktail"%>
          </div>
        </div>
  </div>
        </div>
      </div>
  </div>


<div class="content d-flex">
  <div class="cards">
<% @cocktails.each do |cocktail| %>
  <div class="card-cocktail" style="background-image: url( <%= cl_image_path cocktail.photo.key %>)">

  <h2><%= link_to "#{cocktail.name}", cocktail_path(cocktail), class: "card-link" %></h2>
 </div>
<% end %>
</div>
</div>

<div class="footer">
  <i class="fab fa-facebook"></i>
  <i class="fab fa-twitter-square"></i>
  <i class="fab fa-instagram"></i>
  <p>Delicious cocktails created for enjoyable times</p>
</div>

app/views/cocktails/new.html.erb
<div class="banner2" style="background-image: url(https://images.unsplash.com/photo-1554219962-f71d858fa121?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1600&q=80);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6 my-3">
        <div class="card" style="width: 28rem, height: 18rem;">
          <div class="search-form box-shadow p-4">
            <div class="text-center">
            <h1 class="cocktail-name">Add a Cocktail</h1>
            </div>
            <%= simple_form_for(@cocktail) do |f| %>
             <span class="doses-details"><%= f.input :name %></span>
            <%#= f.association :ingredients %>
             <span class="doses-details"><%= f.input :photo, as: :file %></span>
              <div class="text-center">
              <%= f.submit class: 'btn btn-danger' %>
              <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner3">
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 my-4 p-1">
      <div class="card" style="width: 28rem;, height: 28rem">
        <div class="text-center">
          <h1 class="cocktail-name"><%= @cocktail.name %></h1>
          <div class="cocktail-photo">
            <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill%>
          </div>
            <div class="row justify-content-center">
              <div class="col-sm-12 col-md-6">
                <h1 class="cocktail-name2">Recipe</h1>
              <table class="table table-bordered text-center">
                <tbody>
                  <thead>
                    <th class="cocktail-name3">Ingredient</th>
                    <th class="cocktail-name3">Description</th>
                    <th class="cocktail-name3">Action</th>
                  </thead>
                  <% @cocktail.doses.each do |dose| %>
                  <tr>
                    <td><%= dose.description %></td>
                    <td><%=  dose.ingredient.name %></td>
                    <td>
                    <%= link_to 'Delete Dose', dose_path(dose), method: :delete, data: {confirm: "Are you sure?"} %>
                    <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
              </div>
            <div>
              <%=  link_to "Add Dose", new_cocktail_dose_path(@cocktail), :class => "btn btn-danger" %>
               <%= link_to 'Delete Cocktail', cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn btn-danger" %>
              <%=  link_to "Leave a Review", new_cocktail_review_path(@cocktail), :class => "btn btn-danger" %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
<h3 class="cocktail-name2">Reviews</h3>
  <% if @cocktail.reviews.empty? %>
    <p>Be the first to leave a review</p>
  <% else %>
    <ul class="list-group">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <span class="badge badge-primary badge-pill">
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
              <% counter += 1 %>
            <% end %>
          </span>
          <%= review.content %>
           <%= link_to "Remove",
                  review_path(review),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>
<div>
   <%=  link_to "Cocktails", cocktails_path, :class => "fas fa-cocktail" %>
</div>

<!--

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Nj2U6rhnucI" allowfullscreen></iframe>
</div>

<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/hs8nW9XXtYw" allowfullscreen></iframe>
</div>


 -->

app/views/doses/new.html.erb
<div class="banner2" style="background-image: url(https://images.unsplash.com/photo-1564947742038-b9056e16aaff?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6 my-3">
        <div class="card" style="width: 28rem, height: 25rem;">
          <div class="search-form box-shadow p-4">
            <div class="text-center">
              <h1>Doses</h1>
            </div>
            <%= simple_form_for [@cocktail, @dose] do |f| %>
            <span class="doses-details"><%= f.input :description %></span>
            <span class="doses-details"><%= f.association :ingredient %></span>
              <div class="text-center">
              <%= f.button :submit, class: 'btn btn-danger' %>
              <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>

app/views/reviews/new.html.erb
<div class="banner2" style="background-image: url(https://images.unsplash.com/photo-1577900258307-26411733b430?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-6 my-3">
        <div class="card2" style="width: 28rem, height: 25rem;">
          <div class="search-form box-shadow p-4">
            <div class="text-center">
              <h1>Review</h1>
            </div>
              <%= simple_form_for [ @cocktail, @review ] do |f| %>
                <span class="doses-details"><%= f.input :title %></span>
                <span class="doses-details"><%= f.input :content %></span>
                <span class="doses-details"><%= f.input :rating, label: 'Rating', collection: [1, 2, 3, 4, 5] %></span>
              <div class="text-center">
              <%= f.submit "Submit Review", class: "btn btn-danger" %>
              <% end %>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>